repository:
  name: glpi-graphql
labels:
  - name: bug
    color: f44336
  - name: build
    color: 795548
  - name: cherry-pick
    color: af1c46
  - name: ci
    color: fbca04
  - name: documentation
    color: 607d8b
  - name: duplicate
    color: 9e9e9e
  - name: feature
    color: 3f51b5
  - name: hacktoberfest
    color: ff625f
  - name: invalid
    color: cddc39
  - name: performance
    color: 009688
  - name: question
    color: ff5722
  - name: refactor
    color: 9c27b0
  - name: style
    color: 2196f3
  - name: test
    color: 8bc34a
  - name: wontfix
    color: ffffff
  - name: help wanted
    color: 33aa3f
  - name: good first issue
    color: 7057ff
